### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by DarceyCayl** [uEssentials/uEssentials#530] opened 2016-12-22 01:44 UTC
Other players in my Unturned Server are unable to use the /tpa commands as well as /kit commands. They get the "You don't have permission to use this command" prompt. Any help would be appreciated.

Also, in the Command Reference : 

Name: createkit
Description: Create a kit using your inventory items
Usage: /createkit [name] <cooldown>

I'm not sure what to put for cooldown, any number I put just says invalid number. So if you could explain how to work the cooldown, that'd be dope.

**Comment by leonardosnt** [comment] 2016-12-22 02:05
https://github.com/uEssentials/uEssentials/wiki/Permissions-Reference

**Comment by DarceyCayl** [comment] 2016-12-22 02:07
I saw this, but I'm not sure how to input the permissions.

**Comment by leonardosnt** [comment] 2016-12-22 02:13
You must add in Permisisons.config.xml...

Here is mine, use as reference.

```
<?xml version="1.0" encoding="utf-8"?>
<RocketPermissions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <DefaultGroup>default</DefaultGroup>
  <Groups>
    <Group>
      <Id>default</Id>
      <DisplayName>Guest</DisplayName>
      <Prefix />
      <Suffix />
      <Color>white</Color>
      <Members />
      <Permissions>
        <Permission Cooldown="0">p</Permission>
        <Permission Cooldown="0">compass</Permission>
        <Permission Cooldown="0">rocket</Permission>
        <Permission Cooldown="0">essentials.command.kit</Permission>
        <Permission Cooldown="0">essentials.command.kits</Permission>
        <Permission Cooldown="0">essentials.kit.default2</Permission>
        <Permission Cooldown="0">essentials.kit.default</Permission>
        <Permission Cooldown="0">essentials.kit.xp</Permission>
        <Permission Cooldown="0">balance</Permission>
      </Permissions>
    </Group>
    <Group>
      <Id>vip</Id>
      <DisplayName>VIP</DisplayName>
      <Prefix />
      <Suffix />
      <Color>FF9900</Color>
      <Members>
        <Member>76561198016438091</Member>
      </Members>
      <ParentGroup>default</ParentGroup>
      <Permissions>
        <Permission Cooldown="0">effect</Permission>
        <Permission Cooldown="120">heal</Permission>
        <Permission Cooldown="30">v</Permission>
      </Permissions>
    </Group>
  </Groups>
</RocketPermissions>
```

**Comment by DarceyCayl** [comment] 2016-12-22 02:30
Once I have them all added in, how do I save it to the game? I save the file, do I have to refresh the server?


________________________________

**Comment by leonardosnt** [comment] 2016-12-22 02:34
Use `p reload` on console.

**Comment by DarceyCayl** [comment] 2016-12-22 02:45
<?xml version="1.0" encoding="utf-8"?>
<RocketPermissions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <DefaultGroup>default</DefaultGroup>
  <Groups>
    <Group>
      <Id>default</Id>
      <DisplayName>Guest</DisplayName>
      <Prefix />
      <Suffix />
      <Color>white</Color>
      <Members />
      <Permissions>
        <Permission Cooldown="0">p</Permission>
        <Permission Cooldown="0">compass</Permission>
        <Permission Cooldown="0">rocket</Permission>
        <Permission Cooldown="0">essentials.command.tpa.accept</Permission>
        <Permission Cooldown="0">essentials.command.tpa.send</Permission>
        <Permission Cooldown="0">essentials.command.tpa.cancel</Permission>
        <Permission Cooldown="0">essentials.command.tpa.deny</Permission>
        <Permission Cooldown="2000">essentials.kit.Starter</Permission>
        <Permission Cooldown="0">essentials.command.home</Permission>
      </Permissions>
    </Group>
    <Group>
      <Id>vip</Id>
      <DisplayName>Elite</DisplayName>
      <Prefix>[Elite]</Prefix>
      <Suffix />
      <Color>FF9900</Color>
      <Members>
        <Member>76561198016438091</Member>
      </Members>
      <ParentGroup>default</ParentGroup>
      <Permissions>
      <Permission Cooldown="2000">essentials.kit.Elite</Permission>
      </Permissions>
    </Group>
    <Group>
      <Id>admin</Id>
      <DisplayName>Overlord</DisplayName>
      <Prefix>Overlord</Prefix>
      <Suffix />
      <Color>Red</Color>
      <Members>
        <Member>76561198092772464</Member>
      </Members>
      <Permissions>
        <Permission Cooldown="0">*</Permission>
      </Permissions>
    </Group>
  </Groups>
</RocketPermissions>



This is what it looks like right now. My buddies are still not able to use the permissions. Am I doing it right? I did the p reload, and still they don't have permissions. Also the Display names/Prefixes aren't showing up.


________________________________

**Comment by leonardosnt** [comment] 2016-12-22 02:48
Your forgot

- `essentials.command.tpa` To access /tpa
- `essentials.command.kit` To access /kit
- `essentials.command.kits` To access /kits

**Comment by DarceyCayl** [comment] 2016-12-22 02:57
And the Prefixes?


________________________________

**Comment by leonardosnt** [comment] 2016-12-22 02:59
Which?

**Comment by DarceyCayl** [comment] 2016-12-22 03:03
I was trying to set it up to where if you're VIP [Elite] shows up, and [Overlord] for admin. I don't know, there was a spot for prefixes and display names.


________________________________

**Comment by WGSRangerWolf** [comment] 2016-12-22 03:07
Ah the issue is that you need to do the <prefix> </prefix> And they need to reconnect to the server,

**Comment by leonardosnt** [comment] 2016-12-22 03:07
I think you must reconnect, and prefixes only show for another players.

**Comment by DarceyCayl** [comment] 2016-12-22 03:12
Thanks a lot for the help my man. I really appreciate it.


________________________________

**Comment by leonardosnt** [comment] 2016-12-22 03:14
No problem!

**Comment by Ecxdirerr** [comment] 2016-12-22 03:16
Closing as this has been resolved

**Closed by Ecxdirerr** 2016-12-22 03:16 UTC
