### ISSUE TITLE
Why Clear ev disabled?

### ISSUE THREAD

**Issue by ZSHADOWWOLF** [uEssentials/uEssentials#428] opened 2016-09-02 05:23 UTC
Why Clear ev disabled? If can Enabled say me how?

**Comment by jserodio** [comment] 2016-09-03 18:57
yeah I am currently missing this

**Comment by ZSHADOWWOLF** [comment] 2016-09-04 09:10
Get back them!

**Comment by IlluminatiIzzy** [comment] 2016-09-04 12:07
Will the command return once fixed? I really need it

**Comment by Johnyknowhow** [comment] 2016-09-07 04:10
Not sure what the issue is here, but I'm also trying to figure out why it says it's disabled. Looked through the config to see if it was disabled via an option, but couldn't find anything. Any news?

**Comment by Johnyknowhow** [comment] 2016-09-07 04:19
Nevermind figured it out. Looks like the main uEssentials developer disabled it because he was having issues with it. If you want to re-enable it in it's buggy state you'll have to modify the code found here:[https://github.com/uEssentials/uEssentials/blob/master/src/Commands/MiscCommands.cs#L156-L180](url) and re-compile uEssentials yourself.

**Comment by WGSRangerWolf** [comment] 2016-09-08 03:56
Closing as this is resloved.

**Closed by WGSRangerWolf** 2016-09-08 03:56 UTC
